dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.2.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"
# networks:
#   default: mainnet-fork
